/*
# Marketplace Storage Policies

## Storage Buckets
1. `preview-images` (PUBLIC) — product preview images, accessible via CDN
2. `product-files` (PRIVATE) — premium downloadable model files, access controlled

## Security
- preview-images: public read, admin-only write/delete
- product-files: NO public read. Only admin can write. Downloads via signed URLs through secure-download edge function
- Existing 'order-files' bucket policies preserved
*/

-- Insert bucket records (idempotent)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('preview-images', 'preview-images', true, 52428800, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('product-files', 'product-files', false, 524288000, NULL)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- PREVIEW IMAGES POLICIES (public read, admin write)
-- ============================================================

DROP POLICY IF EXISTS "public_read_preview_images" ON storage.objects;
CREATE POLICY "public_read_preview_images"
  ON storage.objects FOR SELECT
  TO anon, authenticated
  USING (bucket_id = 'preview-images');

DROP POLICY IF EXISTS "admin_upload_preview_images" ON storage.objects;
CREATE POLICY "admin_upload_preview_images"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'preview-images' AND public.is_admin());

DROP POLICY IF EXISTS "admin_update_preview_images" ON storage.objects;
CREATE POLICY "admin_update_preview_images"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (bucket_id = 'preview-images' AND public.is_admin())
  WITH CHECK (bucket_id = 'preview-images' AND public.is_admin());

DROP POLICY IF EXISTS "admin_delete_preview_images" ON storage.objects;
CREATE POLICY "admin_delete_preview_images"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'preview-images' AND public.is_admin());

-- ============================================================
-- PRODUCT FILES POLICIES (private, admin-only)
-- ============================================================

-- NO public SELECT policy — files are private
-- Downloads happen via signed URLs generated by the secure-download edge function

DROP POLICY IF EXISTS "admin_upload_product_files" ON storage.objects;
CREATE POLICY "admin_upload_product_files"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'product-files' AND public.is_admin());

DROP POLICY IF EXISTS "admin_update_product_files" ON storage.objects;
CREATE POLICY "admin_update_product_files"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (bucket_id = 'product-files' AND public.is_admin())
  WITH CHECK (bucket_id = 'product-files' AND public.is_admin());

DROP POLICY IF EXISTS "admin_delete_product_files" ON storage.objects;
CREATE POLICY "admin_delete_product_files"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'product-files' AND public.is_admin());

-- Allow authenticated users to read product-files bucket objects ONLY via signed URLs
-- (Supabase signed URLs work even without a SELECT policy because they use the service role internally)
-- However, for direct storage API access we add a restricted read policy
DROP POLICY IF EXISTS "auth_read_product_files" ON storage.objects;
CREATE POLICY "auth_read_product_files"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id = 'product-files');
